# python/.typos.toml: the trimmed subset a python bootstrap can hit.
# CPY001 is ruff's copyright rule family, not the word "copy"; it appears
# in pyproject.toml's documented ignore list.
[default.extend-identifiers]
CPY001 = "CPY001"
recieve = "recieve"
calender = "calender"
